"""initial schema

Revision ID: 5ae44df0bef0
Revises: 
Create Date: 2026-07-10 12:31:55.694169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae44df0bef0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=True),
    sa.Column('age_group', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_histories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_histories_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_chat_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_dividend_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('paper_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_holding_user_ticker')
    )
    with op.batch_alter_table('paper_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_holdings_user_id'), ['user_id'], unique=False)

    op.create_table('paper_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('initial_cash', sa.BigInteger(), nullable=False),
    sa.Column('final_value', sa.BigInteger(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_rounds_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_round_user_no', ['user_id', 'round_no'], unique=False)

    op.create_table('paper_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=8), nullable=False),
    sa.Column('total_value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_snapshot_user_date')
    )
    with op.batch_alter_table('paper_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('realized_pnl', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_trades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_trade_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_watchlist_user_ticker')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_user_id'))

    op.drop_table('watchlists')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trade_user_created')
        batch_op.drop_index(batch_op.f('ix_paper_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_created_at'))

    op.drop_table('paper_trades')
    with op.batch_alter_table('paper_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_snapshots_user_id'))

    op.drop_table('paper_snapshots')
    with op.batch_alter_table('paper_rounds', schema=None) as batch_op:
        batch_op.drop_index('ix_round_user_no')
        batch_op.drop_index(batch_op.f('ix_paper_rounds_user_id'))

    op.drop_table('paper_rounds')
    with op.batch_alter_table('paper_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_holdings_user_id'))

    op.drop_table('paper_holdings')
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_accounts_user_id'))

    op.drop_table('paper_accounts')
    with op.batch_alter_table('chat_histories', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_user_created')
        batch_op.drop_index(batch_op.f('ix_chat_histories_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_histories_created_at'))

    op.drop_table('chat_histories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
